### ISSUE TITLE
Mac 0.25.1 Macro development Menu Action 

### ISSUE THREAD

**Issue by OfficialVinsmokeSanji** [klayoutmatthias/klayout#104]
Hi 
First of all many thanks to the developers on the software, really appreciate it. 
I am trying to add a shortcut of "Move By" by using Macro Development after reading a post on the forum (https://www.klayout.de/forum/comments.php?DiscussionID=616&page=1#Item_0)

However, i cant find the key binded with Move By, since Mac version doesnt have this " File > Setup > Key bindings." 
Here is my script: 
module MyMacro
  include RBA
app = Application.instance
mw = app.main_window
menu = mw.menu
a = Action.new
a.title = "Move By"
#a.icon = "file path" # If picture icon is desired, else delete this line
a.on_triggered { menu.action("edit_menu.selection_menu.move-by").trigger }
menu.insert_item("@toolbar.end", "moveby", a)
end

Could you please kindly let me know what shoud i put for the move by function? and also where may i find all the key binding info?

**Comment by Kazzz-S** [comment]
Hi,

Does this help?
![mac-customized-menu](https://user-images.githubusercontent.com/16847255/37703177-258a32e2-2d38-11e8-9e94-2f154ccb0dfd.png)

By the way, version 0.25.2 will be available shortly.

Kazzz-S

**Comment by OfficialVinsmokeSanji** [comment]
This is exactly what im looking for. 
Thank you so much!

**Comment by klayoutmatthias** [comment]
It's available now :-)  ... and I will close this issue if you don't mind.

Thanks,

Matthias
