### ISSUE TITLE
Python 3 and GDS shape properties

### ISSUE THREAD

**Issue by klayoutmatthias** [klayoutmatthias/klayout#109]
This bug refers to [https://www.klayout.de/forum/comments.php?DiscussionID=1048](https://www.klayout.de/forum/comments.php?DiscussionID=1048).

The following code won't retrieve the shape property with key 2 on the attached layout with Python 3.

```
lv = pya.LayoutView.current()
for obj in lv.each_object_selected():
  print(repr(obj.shape.property(2)))
```

Reason: the strongly typed keys changed to 64 bit in Python 3 on Windows. On Linux, 32 and 64bit are equivalent (the internal type is long which is == long long). Still the problem exists because of the Windows-induced strong typing.

This is a (slow) workaround:

```
# Don't do this too often:
key = pya.Expression.eval("2")

lv = pya.LayoutView.current()
for obj in lv.each_object_selected():
  print(repr(obj.shape.property(key)))
```
[p2.gds.gz](https://github.com/klayoutmatthias/klayout/files/1883018/p2.gds.gz)

**Comment by thomaslima** [comment]
This is a very obscure bug. Just reproduced on Mac. What is the main use case of shape.property, if you don't mind hinting?

Thanks,
Thomas

**Comment by jurask** [comment]
Some GDS based CAM systems use these properties for storage of some additional information (for example target exposure dose in E beam lithography)

**Comment by thomaslima** [comment]
Thank you @jurask !

**Comment by klayoutmatthias** [comment]
Yes ... basically you can use the properties for any purpose you want. Some tools output net names for example as properties ("annotated GDS"). So you can basically select shapes by their circuit names. But AFAIK there is no common agreement what properties to use.

BTW: the bug should reproduce on Python 3/64 bit. The reason is long/long long differentiation in the compiler (actually there is no difference except on Windows, but the compiler still does not take these values as the same type). I could reproduce the issue on Linux myself.

**Comment by jurask** [comment]
I have tried to build the last git version. It seems like that user properties are now correctly detected in the shape.property function. Unfortunatelly the shape.set_property(2, 'aaa') still creates #l2 instead of #2.

Thanks for any response
Juras

**Comment by klayoutmatthias** [comment]
Hi Juras,

"#l2" should not be an issue. The lower case "l" indicates "long"  
(always 64bit) keys. That's required as OASIS supports long keys and  
Python 3 can potentially generate them.

When you save to GDS and load again, the "long" key will change to  
"#2" because it's normalized to "normal int" (32bit on 32bit Linux and  
on Windows, 64bit on 64bit Linux), but you can still retrieve it with  
property(2) - regardless whether the key is "#l2" or "#2". Both are  
interchangable except for different value range on Windows and 32bit  
Linux.

Thanks for testing,

Matthias




Quoting jurask <notifications@github.com>:
