### ISSUE TITLE
improve tiled XOR results

### ISSUE THREAD

**Issue by stefanottili** [klayoutmatthias/klayout#113]
Feature request:
It would be nice if a tiled XOR would generate the same results as a non tiled or tiled with different tile size.
This can be achieved by OR'ing all results that touch the tile boundaries.

**Comment by klayoutmatthias** [comment]
Thanks for this suggestion. 

Are you referring to DRC or the XOR tool?

**Comment by stefanottili** [comment]
XOR tool ..

and shouldn’t be too hard to do. Just a “do you touch tile boundary check”, adding the touching polygons to a scanline, “or” them and then turn the resulting polygon into error markers.

I never wrapped my head around writing drc rules ..

On Apr 16, 2018, at 15:47, Matthias Köfferlein <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for this suggestion.

Are you referring to DRC or the XOR tool?
