### ISSUE TITLE
pya.DTrans to_itype error

### ISSUE THREAD

**Issue by thomaslima** [klayoutmatthias/klayout#117]
I just encountered this bug. DTrans.to_itype not working properly. Quick fix possible.

<img width="766" alt="screen shot 2018-04-20 at 15 13 46" src="https://user-images.githubusercontent.com/1088659/39069379-958afb26-44ad-11e8-9775-d0a4c41347ec.png">

**Comment by thomaslima** [comment]
I encountered this while trying to feed a DTrans to CellInstArray, but I just realized that there is a DCellInstArray.

**Comment by klayoutmatthias** [comment]
Yes there is :-)
I'll take a look into this. Thanks for reporting.
Best regards,
Matthias

**Comment by thomaslima** [comment]
Thank you @klayoutmatthias
