### ISSUE TITLE
MacOS build for 0.25.3

### ISSUE THREAD

**Issue by klayoutmatthias** [klayoutmatthias/klayout#119]
As a new release is out, I'd like to ask for a binary build for MacOS 10.10+ and 10.13.

Thanks,

Matthias

**Comment by thomaslima** [comment]
Dear Matthias.

Thank you for the new version. Here's my compilation with qt 5.10.1 and python 3.6.4 from homebrew, with python embedded. note that pip changed version and does not allow pip.main anymore.

https://www.dropbox.com/sh/9t3f8yp5edztl6f/AADGWeZpjJgPh5HBwHXGmraYa?dl=0

**Comment by klayoutmatthias** [comment]
Hi kazzz and Thomas,

many thanks for the new builds - I put them on the server already.

Best regards,

Matthias
