### ISSUE TITLE
Feature Request: Read Only for Cells

### ISSUE THREAD

**Issue by raphaelvalentin** [klayoutmatthias/klayout#136]
Hi 
when editing a Top layout, it is still possible to modify the cells (layout view, not box view).
I would be very interested to have a read only option on cell menu. 
What do you think?
Thank you very much,

**Comment by onaspringday** [comment]
I had the same wish before but then I found out an alternative. I now have the 'selection mode' set to 'select top level objects only' and then do in-place editing by selecting an instance of a cell to edit and then access it with Display/Descend (Ctrl+D) . And Display/Ascend (Ctrl+A) to go back up in the hierarchy. 
Would that work for you?

**Comment by raphaelvalentin** [comment]
Yes, absolutely better ... :) I guess my issue is solved.

**Comment by klayoutmatthias** [comment]
Very good! I'll close it then.
