### ISSUE TITLE
Tag Releases

### ISSUE THREAD

**Issue by nsmith5** [klayoutmatthias/klayout#15]
Tagged releases would be helpful if possible. I'd like to build v0.24.- to see if another [plugin](https://github.com/lukasc-ubc/SiEPIC_EBeam_PDK) is failing because of version issues or not but I can't easily find that version.

**Comment by klayoutmatthias** [comment]
0.24 wasn't on GitHub, so there is no tag. The GitHub history starts long after 0.24. The next major release is pending, but don't push me.

**Comment by nsmith5** [comment]
Ah I see, sorry about the noise! Great work by the way!
