### ISSUE TITLE
Bug since version 0.25.3

### ISSUE THREAD

**Issue by ppaulitsch** [klayoutmatthias/klayout#165]
Since version 0.25.3, I have to restart KLayout (editor AND macro development) when I edit a .lym file to take effect.
It happens when I use an external editor (Atom) as well as the internal.
So my procedure is:
Edit the .lym file -> close KLayout macro development and editor -> open KLayout editor -> start macro
otherwise it would not accept the changes in the .lym file.
It also affects version 0.25.4. Is there a bugfix or workaround for this problem?

**Comment by klayoutmatthias** [comment]
Hi,

what do you mean by "take effect"? 

If you edit a .lym file inside KLayout, the tool will see the content you have edited. So for example if you tied the macro to a menu, you will always execute the current file. If you edit a .lym macro externally, KLayout will notice that and ask whether to reload the file. If not, check if you have enabled auto-refresh in File/Setup, Application/Macro Development IDE, General tab, option "Check macros for updates and ask whether to refresh".

But I assume you mean something else - like PCell code or similar. Could you be somewhat more specific?

Thanks,

Matthias

**Comment by ppaulitsch** [comment]
Hi Matthias!

You said "So for example if you tied the macro to a menu, you will always execute the current file."
At my computer, and all the computers at my institute, this does not happen. If we edit a macro in the macro editor, the changes are not applied (by execution of the macro) until we close all KLayout instances and open it again.The file location (locally or net drive) does not have an effect, neither the option "Check macros for updates and ask whether to refresh".
It is Ruby code and affects both .rb and .lym files.

glg
Peter    Am Sonntag, 16. September 2018, 21:54:01 MESZ hat Matthias Köfferlein <notifications@github.com> Folgendes geschrieben:  
 
 
Hi,

what do you mean by "take effect"?

If you edit a .lym file inside KLayout, the tool will see the content you have edited. So for example if you tied the macro to a menu, you will always execute the current file. If you edit a .lym macro externally, KLayout will notice that and ask whether to reload the file. If not, check if you have enabled auto-refresh in File/Setup, Application/Macro Development IDE, General tab, option "Check macros for updates and ask whether to refresh".

But I assume you mean something else - like PCell code or similar. Could you be somewhat more specific?

Thanks,

Matthias

**Comment by klayoutmatthias** [comment]
Hi Peter,

just to confirm - this is what works for me (0.25.4 on Ubuntu 16):

* Open the application
* Choose Tools/Macro Development
* Create a new Ruby macro with a single-liner (```RBA::MessageBox::info("Info", "A message box", RBA::MessageBox::Ok)```)
* I save this macro
* Configure this macro in the properties as
  * "Description": "Test macro"
  * "Show in Menu": ON
* Now I see a menu item in "Tools/Macros" as "Test macro". If I select this, a message box with "A message box" is shown.
* I change the macro text in the macro IDE to ```RBA::MessageBox::info("Info", "The answer is 42", RBA::MessageBox::Ok)```
* I save this macro
* I select "Test macro" from the "Tools/Macros" again. 
* The message box says "The answer is 42"

So the new script has been loaded and is executed accordingly.

If you see that not working, maybe something is wrong with the setup. You can try several things:
* Check whether there are strange error messages when you started KLayout (use the log viewer on Windows from File/Log Viewer)
* Try with a blank configuration: ```klayout -c path\to\some\file\which\does\not\exist```
* Try without load implicit macros: ```klayout -rx```
* Try with a blank environment: ```KLAYOUT_HOME=path\to\some\empty\directory klayout```

Matthias

**Comment by ppaulitsch** [comment]
Hi Matthias!

I guess now I identified the problem: We got path problems with relative paths of included auxiliary .rb files since version 0.25.3 and switched from the "load" command to "require_relative" to solve this problem.But I guess using "require_relative" demands a restart of the program, because we didn't encounter this problem using the command "load".
Is there an elegant way to use relative paths using the old "load" command? We don't want to use absolute paths ;)
glg
Peter    Am Montag, 17. September 2018, 22:01:33 MESZ hat Matthias Köfferlein <notifications@github.com> Folgendes geschrieben:  
 
 
Hi Peter,

just to confirm - this is what works for me (0.25.4 on Ubuntu 16):
   
   - Open the application
   - Choose Tools/Macro Development
   - Create a new Ruby macro with a single-liner (RBA::MessageBox::info("Info", "A message box", RBA::MessageBox::Ok))
   - I save this macro
   - Configure this macro in the properties as      
      - "Description": "Test macro"
      - "Show in Menu": ON

   - Now I see a menu item in "Tools/Macros" as "Test macro". If I select this, a message box with "A message box" is shown.
   - I change the macro text in the macro IDE to RBA::MessageBox::info("Info", "The answer is 42", RBA::MessageBox::Ok)
   - I save this macro
   - I select "Test macro" from the "Tools/Macros" again.
   - The message box says "The answer is 42"

So the new script has been loaded and is executed accordingly.

If you see that not working, maybe something is wrong with the setup. You can try several things:
   
   - Check whether there are strange error messages when you started KLayout (use the log viewer on Windows from File/Log Viewer)
   - Try with a blank configuration: klayout -c path\to\some\file\which\does\not\exist
   - Try without load implicit macros: klayout -rx
   - Try with a blank environment: KLAYOUT_HOME=path\to\some\empty\directory klayout

Matthias

**Comment by klayoutmatthias** [comment]
Hi Peter,

That actually is a good explanation :-)

In general, "require" is bad for developing inside the active interpreter. I came across this issue myself, but I came up with the same "load" workaround so far. Maybe there is a way to tell Ruby to clear the require cache, but I'm not aware of that.

But loading a file relative to the origin is easy. I use a load call like this:

```
load(File.join(File.dirname(__FILE__), "other.rb"))
```

There is one more issue when reloading a file: when you define a class in a file and reload it, the class will not be replaced entirely. Instead, it's reopened and the methods are modified. So if you drop a method and rerun the script, the method will actually still be there until the next restart. This causes unexpected errors when part of your code uses this yet-to-be-deleted method. 

If your class resides in a module, you can use code like this to redefine your class (taken from QRCode PCell):

```(ruby)
module QRCodeLibModule
  QRCodeLibModule.constants.member?(:QRCode) && remove_const(:QRCode)
  class QRCode 
     ... class body ...
  end
end
```

Regards,

Matthias

**Comment by klayoutmatthias** [comment]
Ok to close this issue?

**Comment by ppaulitsch** [comment]
Thank you, this works perfect! :)
Yes, close this issue.    Am Mittwoch, 19. September 2018, 21:54:43 MESZ hat Matthias Köfferlein <notifications@github.com> Folgendes geschrieben:  
 
 
Ok to close this issue?
