### ISSUE TITLE
./build.sh -qt5 picks up qmake-qt4 on debian sid

### ISSUE THREAD

**Issue by svenn71** [klayoutmatthias/klayout#17]
Issuing ./build.sh -qt5 will pick up qmake-qt4 on debian sid due to the sequence of switch parsing.
If ./build.sh -qmake qmake is issued, things will be ok.
There is no such thing as qmake-qt5 on debian sid, it is called qmake, and that is behind qmake-qt4 in the checking sequence when -qmake is not issued.

**Comment by klayoutmatthias** [comment]
-qt5 does not make build.sh use Qt5 - it's rather a hint if the version can't be auto-detected. Use "build.sh -qmake x" to select the Qt version you want to use.

I have updated the "build.sh -h" text so this more clearer I hope.
