### ISSUE TITLE
Creating structures with Python 

### ISSUE THREAD

**Issue by isanch** [klayoutmatthias/klayout#19]
Dear Matthias,

I would like to use a Python code to create structures that are easy to code but difficult to implement by hand (e.g. concentric squares as the ones in this [link](https://www.google.de/search?q=concentric+squares+pattern&rlz=1C1CHBF_enDE767DE767&tbm=isch&source=iu&pf=m&ictx=1&fir=NPds5SE1kprqvM%253A%252CADERV-XVollX6M%252C_&usg=__UYKZaEYGtLShTN6eis4QmdFuyYM%3D&sa=X&ved=0ahUKEwiExpD5sMPXAhUB16QKHdXSAoQQ9QEIKTAA#imgrc=NPds5SE1kprqvM:)). 

I have started to read about the macros, but I am having some issues trying to implement the examples. First, I tried to run some codes, e.g. the one in Documentation>Programming scripts >Using Python> [Writing macros in Python](http://www.klayout.de/doc-qt4/programming/python.html). If a create a new python macros in the local folder, copy paste the code and run it, nothing happens and nothing is shown in the console. If I enter the code manually in the console, nothing happens either.  What is the issue? I was expecting it to create a layout, cell and layer and a rectangle on it...

Thanks in advance for your help.

Irene

**Comment by klayoutmatthias** [comment]
Hi Irene,

is this a bug? 

I assume you are referring to the first example - this is about writing a small file, not about showing it in the window. So I don't see a bug here.

Please use this issue tracker it to report bugs or to create feature requests. Things that need coding.
