### ISSUE TITLE
Autorun(-early) doesn't seem to run when lym files are inside a package

### ISSUE THREAD

**Issue by davidnhutch** [klayoutmatthias/klayout#21]
Something is broken about the macro autorun feature, under certain circumstances, in 0.25

Assumed problem:

It seems  the autorun-on-startup feature probably only looks in KLayout/macros folder right now. I think it should also look in KLayout/salt/package-name/macros and KLayout/group-name/package-name/macros. This enables dependencies between packages without needing to "load 'filename.rb'" to manually run one code from the other code.

Steps to reproduce the problem:

1) Create file1.lym and file2.lym under macros folder (the main macros folder, not inside a package)

file1.lym:

    # Choose properties > Run early on startup
    module MyModule
      class MyClass
        def MyMethod
          p 'hello world'
        end
      end
    end

file2.lym:

    include MyModule
    MyClass.new.MyMethod

2) Make file1.lym be auto-run early.
3) Close then open KL.
4) Run file2.lym via the Macro Editor. It works! (Nothing is wrong.)
5) Now, create a package named "mypackage" using Tools > Manage Packages. Use the Ruby template.
6) Move file1.lym and file2.lym to salt/mypackage/macros using the OS filesystem. (Or create them anew there and delete the old ones.)
7) Close then open KL.
8) Try to run file2.lym via the Macro Editor. It doesn't work. (Apparently file1.lym has not run, so it doesn't recognize MyModule.) 
9) Now, if you manually run file1.lym in the Macro Editor, then run file2.lym, it works. This indicates that there is nothing broken about the code. It is just that file1.lym is not autorunning on startup.

**Comment by klayoutmatthias** [comment]
I see. You're are probably referring to our discussion in the forum :-) 

My suggestion would be to use plain ruby libraries in the "ruby" subfolder. They can be included through the standard "require". 

But I'll take a look at the issue. Thanks for reporting the problem.

**Comment by klayoutmatthias** [comment]
I have tried to provide a fix on the master branch. The fix goes a bit deeper than I was expecting. Maybe you have a chance to test it and give feedback.

Thanks, 

Matthias
