### ISSUE TITLE
klayout cannot open CIF files exported by LASI tlc2cif

### ISSUE THREAD

**Issue by coldlogix** [klayoutmatthias/klayout#28]
LASI generates CIF files which fail to be identified as CIF by klayout.

LASI has a tool, tlc2cif, that outputs files like the one attached (lasi.cif.txt -- note, I had to add the .txt suffix so github would upload it, though klayout is perfectly happy with the .txt extension using klayout -e lasi.cif.txt)

The CIF file unfortunately contains
DS#1 2/2;
as the first part of the 'signature', and while the klayout cif parser can parse this, the klayout code that checks to see if this is a CIF file is more restrictive, wanting "DS \<number\>" instead of D\<seperator\>S\<seperator\>\<number\>

Simply changing 
DS#1 2/2;
to
DS 1 2/2;

allows klayout to properly identify, and then parse and open the file, but as far as I can tell, there's nothing illegal about using # as a separator as LASI does.  And the only problem is that klayout doesn't recognize the file as a CIF file because it fails to find the "DS #" signature.
(lasi-klayout.cif.txt has this change made)

[lasi.cif.txt](https://github.com/klayoutmatthias/klayout/files/1504281/lasi.cif.txt)
[lasi-klayout.cif.txt](https://github.com/klayoutmatthias/klayout/files/1504282/lasi-klayout.cif.txt)

**Comment by klayoutmatthias** [comment]
Thanks for the issue. The solution goes a bit beyond the pull request - basically there were more issues. Now file format detection should be closer to the full specification. Still the requirement is that the first command is either "L" or "DS".

I have also included your file as a test case.
