### ISSUE TITLE
pya.Trans(10000,10000)

### ISSUE THREAD

**Issue by lukasc-ubc** [klayoutmatthias/klayout#44]
The following works on KLayout 0.24

`import pya`
`pya.Trans(10000,10000)`

but doesn't work on KLayout 0.25 on Windows, and returns the error:

`function takes exactly 0 arguments (2 given)`

http://www.klayout.de/doc-qt4/code/class_Trans.html

**Comment by klayoutmatthias** [comment]
Yes, you're right. The reason is a type clash between Trans(x, y) and Trans(other_trans, displacement). The workaround is to use a vector for the argument:

```
pya.Trans(pya.Vector(x, y))
```
