### ISSUE TITLE
Include numpy in Python version packaged with Windows

### ISSUE THREAD

**Issue by klayoutmatthias** [klayoutmatthias/klayout#81]

**Comment by thomaslima** [comment]
Same for MacOS. I couldn't figure that out yet.

**Comment by thomaslima** [comment]
Figured it out for macOS. my last .dmg was only 100mb. #100 

This is a big deal for salt packages.

**Comment by klayoutmatthias** [comment]
numpy is included in 0.25.3

**Comment by thomaslima** [comment]
Hi Matthias, so does that mean that klayout ships with its own python virtualenv in the windows build?

**Comment by klayoutmatthias** [comment]
Hi Thomas,

That's true if "virtualenv" is just another word for "take what you get" :-)

I just included numpy in the installer. So it's available, although I  
don't know whether the version I picked isn't already outdated. Sadly,  
the MSYS2 platform I'm using is making rolling releases and being  
happy with the one I had, I did not follow their release cycles. Maybe  
I'll setup my CI to update the installation regularly. That should  
make KLayout follow MSYS2.

Frankly, I'd like to have KLayout available as MSYS2 package - then  
people could just install that themselves and use all those nice  
Python packages from MSYS2. But I have not made an attempt yet to  
initiate this.

Until then, building KLayout for MSYS2 isn't a big deal as MSYS2 is  
pretty much Linux-like. It just takes a while.

Best regards,

Matthias


Quoting Thomas Ferreira de Lima <notifications@github.com>:

**Comment by thomaslima** [comment]
I am asking because I included python's framework in the mac build I've been providing. That means that people can install packages via pip. that is why I did not submit a pull request #100  until the other OS had the same functionality. But actually if you think it's okay I can do it.
