### ISSUE TITLE
Debugging screenshot on MacOS

### ISSUE THREAD

**Issue by thomaslima** [klayoutmatthias/klayout#89]
Screenshots triggered by MacOS fails to display colors in the masks, unless oversampling is set. The oversampling feature can be activated by using oversampling from the settings: Settings -> Display -> General -> 2x oversampling.

The first screenshot was produced from klayout itself with File -> Screenshot. Works as intended

![screenshot_from_klayout](https://user-images.githubusercontent.com/1088659/37131239-804ffa1a-2255-11e8-8f29-ac48d993eb1b.png)

The second screenshot shows the same screenshot without oversampling. Also works!
![screenshot_from_klayout_no_oversampling](https://user-images.githubusercontent.com/1088659/37131517-ae444808-2256-11e8-9749-0e455ee488df.png)

The following three screenshots were taken from the OS. The first one shows a fully white screen, but what is actually happening is that where there should be color, it is transparent. Note that the layer icons on the right render fine if their lines are selected.

<img width="1349" alt="oversampling1x" src="https://user-images.githubusercontent.com/1088659/37131254-90c4f5da-2255-11e8-8dc3-ba0e861f6537.png">
<img width="1349" alt="oversampling2x" src="https://user-images.githubusercontent.com/1088659/37131242-834a5242-2255-11e8-8b12-95b57843ea0b.png">
<img width="1349" alt="oversampling3x" src="https://user-images.githubusercontent.com/1088659/37131253-90b143d2-2255-11e8-9130-577b5e2820d4.png">

**Comment by klayoutmatthias** [comment]
Hi Thomas,

are you saying the screen shows the colors, while the screenhot (taken by MacOS) doesn't? 

Is this some kind of offscreen rendering thing? I basically use QImage rendering. My theory is that although I am using RGB32 type (without alpha), the upper 8 bits of the 32bit pixel value might matter too. The are sometimes set to 0xff, but sometimes they aren't. On the platforms I know these bits are 
ignored. Maybe not on Mac.

I have set up a branch "bug_89" where I have tried a patch to force the upper bits to ones: https://github.com/klayoutmatthias/klayout/commit/8bec89611fdf947a3f0c2ace1308c188a2922b72

Maybe you can try this.

Best regards,

Matthias

**Comment by thomaslima** [comment]
Thank you. I will check it out once I figure out how to get rid of the bug described in my comment in #85

**Comment by thomaslima** [comment]
Alright. This fixed it for me in Qt 5.9.4. Thank you! It would have taken me forever to find that one.
My problem with Qt 5.10 was something similar to this (rendering with canvas). Will try again there now.
